sonata_admin:
    title: 'Delivery gestión'
    dashboard:
        blocks:
            - class: col-lg-3 col-xs-3
              position: top
              type: sonata.admin.block.stats
              settings:
                  code: admin.cliente
                  icon: fa fa-user
                  text: 'Clientes'
                  color: bg-green

            - class: col-lg-3 col-xs-3
              position: top
              type: sonata.admin.block.stats
              settings:
                code: admin.restaurante
                icon: fa fa-utensils
                text: 'Restaurantes'
                color: bg-yellow

            - class: col-lg-3 col-xs-3
              position: center
              type: sonata.admin.block.admin_preview
              settings:
                code: admin.plato
                icon: fa fa-utensils
                text: 'Ultimos platos'
                limit: 10
                filters:
                  _sort_by: id
                  _sort_order: DESC




sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
